name: Test App
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       
     - name: Setup Node.js 
       uses: actions/checkout@v4
       with:
        node-version: 18

     - name: Check node
       run: node -v

     - name: Install
       run: npm install
     
     - name: test
       run: npm test

    
       

