name: Test App
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
       
     - name: Setup Node.js 
       uses: actions/checkout@v4
       with:
        node-version: 18

     - name: Check node
       run: node -v

     - name: Install
       run: npm install
     
     - name: test
       run: npm test

     - name: Build app
       run: docker build -t test-app .

     - name: Scan Docker image with Trivy
       uses: aquasecurity/trivy-action@0.28.0
       with:
          image-ref: 'test-app'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  


    
       

